### ISSUE TITLE
HI it seems that something wrong in the Windows Platform.

### ISSUE THREAD

**Issue by ryanlin821** [bianjiang/tweetf0rm#15]
HI,Prof. bianjiang,

really thank you for your open sourse, firstly.

I test this program on the Mac Platform. It runs well.

However, I try to run it on the windows platform. It seems something wrong.

Here is the error log.

I tried many ways to fix it, but all failed.

Could you help me ? T.T

Thank you !!! :)

ERROR-[2017-04-05 06:30:42,088][scheduler][__init__][56]: Can't pickle <function <lambda> at 0x0000000003D7AB38>: it's not found as redis.client.<lambda>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\multiprocessing\forking.py", line 381, in main
    self = load(from_parent)
  File "C:\Python27\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\Python27\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\Python27\lib\pickle.py", line 886, in load_eof
    raise EOFError
EOFError

**Comment by ryanlin821** [comment]
My python version is 2.7.13 
Thank you :)

**Comment by bianjiang** [comment]
Not tested on Windows.
